name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: deploy-lambda-function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        working-directory: ./function/
        with:
          node-version: "20.x"
        run: ls
        # uses: actions/setup-node@v3
      # - run: npm ci
      # - run: npm run build --if-present
      # - run: npm test

    # - name: serverless deploy
    #   uses: serverless/github-action@master
    #   with:
    #     args: deploy
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
